language: node_js
node_js:
  - 14

install:
  - npm install
jobs:
  include:
    - stage: build & test
      script: npm run lint

    - stage: build & test
      script: npm run build
    - stage: build & test
      script: npm run coverage
    - stage: deploy
      deploy:
        provider: npm
        email: "samuraitruong@hotmail.com"
        api_key: $NPM_API_TOKEN
        on:
          branch: master
