language: node_js
node_js:
  - latest

cache: yarn

before_script:
  - npm install -g yarn
install:
  - yarn
jobs:
  include:
    - stage: build & test
      script: npm run build
    - stage: build & test
      script: npm test
